function c=copyright()
% c = obj.copyright()
%
% Returns the copyright text in a string.
%
c= [ '\nmaxCorr: Copyright (C) 2012, Mika Seppa, Brain Research Unit,\n' ...
   'O.V. Lounasmaa Laboratory, Aalto University, Finland.\n\n' ...
   'maxCorr is free software: you can redistribute it and/or modify\n' ...
   'it under the terms of the GNU General Public License as published by\n' ...
   'the Free Software Foundation, either version 3 of the License, or\n' ...
   '(at your option) any later version.\n\n' ...
   'maxCorr is distributed in the hope that it will be useful,\n' ...
   'but WITHOUT ANY WARRANTY; without even the implied warranty of\n' ...
   'MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n' ...
   'GNU General Public License for more details.\n\n' ...
   'You should have received a copy of the GNU General Public License\n' ...
   'along with maxCorr. If not, see <http://www.gnu.org/licenses/>.\n\n' ];
   